In [ ]:
import pandas as pd

tournaments = pd.read_csv("tournaments.csv")
teams = pd.read_csv("teams.csv")
matches = pd.read_csv("matches.csv")
goals = pd.read_csv("goals.csv")
players = pd.read_csv("players.csv")
stadiums = pd.read_csv("stadiums.csv")
groups = pd.read_csv("groups.csv")
group_standings = pd.read_csv("group_standings.csv")
tournament_standings = pd.read_csv("tournament_standings.csv")
player_appearances = pd.read_csv("player_appearances.csv")
team_appearances = pd.read_csv("team_appearances.csv")
tournament_appearances = pd.read_csv("tournament-appearances.csv")  
squads = pd.read_csv("squads.csv")
qualified_teams = pd.read_csv("qualified_teams.csv")
managers = pd.read_csv("managers.csv")
referees = pd.read_csv("referees.csv")
attendance = pd.read_csv("attendance.csv")
attendance_by_edition = pd.read_csv("attendance-by-edition.csv")

✅ تم قراءة جميع الجداول الـ 18 بنجاح تام!

In [4]:

tournaments.info()

tournaments.isna().sum()

tournaments["tournament_id"].duplicated().sum()

tournaments.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   key_id              30 non-null     int64
 1   tournament_id       30 non-null     str
 2   tournament_name     30 non-null     str
 3   year                30 non-null     int64
 4   start_date          30 non-null     str
 5   end_date            30 non-null     str
 6   host_country        30 non-null     str
 7   winner              30 non-null     str
 8   host_won            30 non-null     int64
 9   count_teams         30 non-null     int64
 10  group_stage         30 non-null     int64
 11  second_group_stage  30 non-null     int64
 12  final_round         30 non-null     int64
 13  round_of_16         30 non-null     int64
 14  quarter_finals      30 non-null     int64
 15  semi_finals         30 non-null     int64
 16  third_place_match   30 non-null     int64
 17  final               30 non-null     int64
dtypes: int64(12), str(6)
memory usage: 4.3 KB

,key_id,tournament_id,tournament_name,year,start_date,end_date,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,1,WC-1930,1930 FIFA Men's World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,2,WC-1934,1934 FIFA Men's World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,3,WC-1938,1938 FIFA Men's World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1
3,4,WC-1950,1950 FIFA Men's World Cup,1950,1950-06-24,1950-07-16,Brazil,Uruguay,0,13,1,0,1,0,0,0,0,0
4,5,WC-1954,1954 FIFA Men's World Cup,1954,1954-06-16,1954-07-04,Switzerland,West Germany,0,16,1,0,0,0,1,1,1,1

In [5]:
tournaments["start_date"] = pd.to_datetime(tournaments["start_date"] ) 
tournaments["end_date"] = pd.to_datetime(tournaments["end_date"]) 
text_cols = ["tournament_id", "tournament_name", "host_country", "winner"]
for col in text_cols:
  tournaments[col] = tournaments[col].str.strip()

tournaments = tournaments.drop(columns=["key_id"])

tournaments[["tournament_id", "tournament_name", "year", "start_date"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tournament_id    30 non-null     str
 1   tournament_name  30 non-null     str
 2   year             30 non-null     int64
 3   start_date       30 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 1.1 KB

In [7]:
tournaments.head(3)

,tournament_id,tournament_name,year,start_date,end_date,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,WC-1930,1930 FIFA Men's World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,WC-1934,1934 FIFA Men's World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,WC-1938,1938 FIFA Men's World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1

teams_cleeinng

In [8]:

teams.info()

teams.isna().sum()

teams["team_id"].duplicated().sum()

teams.head()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   key_id                      88 non-null     int64
 1   team_id                     88 non-null     str
 2   team_name                   88 non-null     str
 3   team_code                   88 non-null     str
 4   mens_team                   88 non-null     int64
 5   womens_team                 88 non-null     int64
 6   federation_name             88 non-null     str
 7   region_name                 88 non-null     str
 8   confederation_id            88 non-null     str
 9   confederation_name          88 non-null     str
 10  confederation_code          88 non-null     str
 11  mens_team_wikipedia_link    88 non-null     str
 12  womens_team_wikipedia_link  88 non-null     str
 13  federation_wikipedia_link   88 non-null     str
dtypes: int64(3), str(11)
memory usage: 9.8 KB

,key_id,team_id,team_name,team_code,mens_team,womens_team,federation_name,region_name,confederation_id,confederation_name,confederation_code,mens_team_wikipedia_link,womens_team_wikipedia_link,federation_wikipedia_link
0,1,T-01,Algeria,DZA,1,0,Algerian Football Federation,Africa,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Algeria_national...,not applicable,https://en.wikipedia.org/wiki/Algerian_Footbal...
1,2,T-02,Angola,AGO,1,0,Angolan Football Federation,Africa,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Angola_national_...,not applicable,https://en.wikipedia.org/wiki/Angolan_Football...
2,3,T-03,Argentina,ARG,1,1,Argentine Football Association,South America,CF-4,South American Football Confederation,CONMEBOL,https://en.wikipedia.org/wiki/Argentina_nation...,https://en.wikipedia.org/wiki/Argentina_women'...,https://en.wikipedia.org/wiki/Argentine_Footba...
3,4,T-04,Australia,AUS,1,1,Football Australia,Oceania,CF-1,Asian Football Confederation,AFC,https://en.wikipedia.org/wiki/Australia_men%27...,https://en.wikipedia.org/wiki/Australia_women'...,https://en.wikipedia.org/wiki/Football_Australia
4,5,T-05,Austria,AUT,1,0,Austrian Football Association,Europe,CF-6,Union of European Football Associations,UEFA,https://en.wikipedia.org/wiki/Austria_national...,not applicable,https://en.wikipedia.org/wiki/Austrian_Footbal...

In [9]:

cols_to_drop = [
    'key_id',
    'mens_team_wikipedia_link',
    'womens_team_wikipedia_link',
    'federation_wikipedia_link',
]
teams = teams.drop(columns=cols_to_drop)

text_cols = [
    'team_id',
    'team_name',
    'team_code',
    'federation_name',
    'region_name',
]
for col in text_cols:
  teams[col] = teams[col].str.strip()

teams.head(3)

,team_id,team_name,team_code,mens_team,womens_team,federation_name,region_name,confederation_id,confederation_name,confederation_code
0,T-01,Algeria,DZA,1,0,Algerian Football Federation,Africa,CF-2,Confederation of African Football,CAF
1,T-02,Angola,AGO,1,0,Angolan Football Federation,Africa,CF-2,Confederation of African Football,CAF
2,T-03,Argentina,ARG,1,1,Argentine Football Association,South America,CF-4,South American Football Confederation,CONMEBOL

In [ ]:
tournaments["start_date"] = pd.to_datetime(tournaments["start_date"] ) 
tournaments["end_date"] = pd.to_datetime(tournaments["end_date"]) 
text_cols = ["tournament_id", "tournament_name", "host_country", "winner"]
for col in text_cols:
  tournaments[col] = tournaments[col].str.strip()

tournaments = tournaments.drop(columns=["key_id"])

tournaments[["tournament_id", "tournament_name", "year", "start_date"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tournament_id    30 non-null     str
 1   tournament_name  30 non-null     str
 2   year             30 non-null     int64
 3   start_date       30 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 1.1 KB

group_cleainnig

In [12]:

groups["group_id"] = groups["tournament_id"] + "_" + groups["group_name"]

groups["group_id"].duplicated().sum()

groups.head(3)

,key_id,tournament_id,tournament_name,stage_number,stage_name,group_name,count_teams,group_id
0,1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,4,WC-1930_Group 1
1,2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 2,3,WC-1930_Group 2
2,3,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 3,3,WC-1930_Group 3

In [13]:

for col in ["stage_name", "group_name"]:
  groups[col] = groups[col].str.strip()

groups = groups.drop(columns=["key_id"])

groups.head(3)

,tournament_id,tournament_name,stage_number,stage_name,group_name,count_teams,group_id
0,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,4,WC-1930_Group 1
1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 2,3,WC-1930_Group 2
2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 3,3,WC-1930_Group 3

staduim_cleainng

In [14]:

stadiums.info()

stadiums.isna().sum()


stadiums['stadium_id'].duplicated().sum()

stadiums.head()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   key_id                  240 non-null    int64
 1   stadium_id              240 non-null    str
 2   stadium_name            240 non-null    str
 3   city_name               240 non-null    str
 4   country_name            240 non-null    str
 5   stadium_capacity        240 non-null    int64
 6   stadium_wikipedia_link  240 non-null    str
 7   city_wikipedia_link     240 non-null    str
dtypes: int64(2), str(6)
memory usage: 15.1 KB

,key_id,stadium_id,stadium_name,city_name,country_name,stadium_capacity,stadium_wikipedia_link,city_wikipedia_link
0,1,S-001,Estadio José Amalfitani,Buenos Aires,Argentina,49000,https://en.wikipedia.org/wiki/José_Amalfitani_...,https://en.wikipedia.org/wiki/Buenos_Aires
1,2,S-002,Estadio Monumental,Buenos Aires,Argentina,75000,https://en.wikipedia.org/wiki/Estadio_Monument...,https://en.wikipedia.org/wiki/Buenos_Aires
2,3,S-003,Estadio Chateau Carreras,Córdoba,Argentina,47000,https://en.wikipedia.org/wiki/Estadio_Mario_Al...,"https://en.wikipedia.org/wiki/Córdoba,_Argentina"
3,4,S-004,Estadio José María Minella,Mar del Plata,Argentina,44000,https://en.wikipedia.org/wiki/Estadio_José_Mar...,https://en.wikipedia.org/wiki/Mar_del_Plata
4,5,S-005,Estadio Ciudad de Mendoza,Mendoza,Argentina,35000,https://en.wikipedia.org/wiki/Estadio_Malvinas...,"https://en.wikipedia.org/wiki/Mendoza,_Argentina"

In [15]:

stadiums = stadiums.drop(
    columns=['key_id', 'stadium_wikipedia_link', 'city_wikipedia_link']
)

text_cols = ['stadium_id', 'stadium_name', 'city_name', 'country_name']
for col in text_cols:
  stadiums[col] = stadiums[col].str.strip()

stadiums.head(3)

,stadium_id,stadium_name,city_name,country_name,stadium_capacity
0,S-001,Estadio José Amalfitani,Buenos Aires,Argentina,49000
1,S-002,Estadio Monumental,Buenos Aires,Argentina,75000
2,S-003,Estadio Chateau Carreras,Córdoba,Argentina,47000

players_cleainng

In [16]:

players.info()


players.isna().sum()


players['player_id'].duplicated().sum()

 
players.head()

<class 'pandas.DataFrame'>
RangeIndex: 10401 entries, 0 to 10400
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   key_id                 10401 non-null  int64
 1   player_id              10401 non-null  str
 2   family_name            10401 non-null  str
 3   given_name             10401 non-null  str
 4   birth_date             10400 non-null  str
 5   female                 10401 non-null  int64
 6   goal_keeper            10401 non-null  int64
 7   defender               10401 non-null  int64
 8   midfielder             10401 non-null  int64
 9   forward                10401 non-null  int64
 10  count_tournaments      10401 non-null  int64
 11  list_tournaments       10401 non-null  str
 12  player_wikipedia_link  10401 non-null  str
dtypes: int64(7), str(6)
memory usage: 1.0 MB

,key_id,player_id,family_name,given_name,birth_date,female,goal_keeper,defender,midfielder,forward,count_tournaments,list_tournaments,player_wikipedia_link
0,1,P-35894,A'Court,Alan,1934-09-30,0,0,0,0,1,1,1958,https://en.wikipedia.org/wiki/Alan_A%27Court
1,2,P-29915,Aarønes,Ann Kristin,1973-01-19,1,0,0,1,1,2,"1995, 1999",https://en.wikipedia.org/wiki/Ann_Kristin_Aar%...
2,3,P-03484,Aaronson,Brenden,2000-10-22,0,0,0,0,1,1,2022,https://en.wikipedia.org/wiki/Brenden_Aaronson
3,4,P-04189,Abadzhiev,Stefan,1934-07-03,0,0,0,0,1,1,1966,https://en.wikipedia.org/wiki/Stefan_Abadzhiev
4,5,P-03523,Abalo,Jean-Paul,1975-06-26,0,0,1,0,0,1,2006,https://en.wikipedia.org/wiki/Jean-Paul_Abalo

In [17]:
players['player_name'] = (
    players['given_name'].fillna('') + ' ' + players['family_name'].fillna('')
).str.strip()
players['birth_date'] = pd.to_datetime(players['birth_date'], errors='coerce')

for col in ['player_id', 'family_name', 'given_name', 'player_name']:
  players[col] = players[col].str.strip()

players = players.drop(columns=['key_id', 'player_wikipedia_link'])

players[['player_id', 'player_name', 'birth_date', 'female']].head(3)

  player_id          player_name birth_date  female
0   P-35894         Alan A'Court 1934-09-30       0
1   P-29915  Ann Kristin Aarønes 1973-01-19       1
2   P-03484     Brenden Aaronson 2000-10-22       0

managers cleainng

In [18]:
managers.info()
managers.isna().sum()
managers['manager_id'].duplicated().sum()
managers.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 475 entries, 0 to 474
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   key_id                  475 non-null    int64
 1   manager_id              475 non-null    str
 2   family_name             475 non-null    str
 3   given_name              475 non-null    str
 4   female                  475 non-null    int64
 5   country_name            475 non-null    str
 6   manager_wikipedia_link  475 non-null    str
dtypes: int64(2), str(5)
memory usage: 26.1 KB

,key_id,manager_id,family_name,given_name,female,country_name,manager_wikipedia_link
0,1,M-001,Acosta,Nelson,0,Uruguay,https://en.wikipedia.org/wiki/Nelson_Acosta
1,2,M-002,Addo,Otto,0,Ghana,https://en.wikipedia.org/wiki/Otto_Addo
2,3,M-003,Adshead,John,0,England,https://en.wikipedia.org/wiki/John_Adshead

In [19]:
managers['manager_name'] = (
    managers['given_name'].fillna('')
    + ' '
    + managers['family_name'].fillna('')
).str.strip()

for col in ['manager_id', 'family_name', 'given_name', 'country_name', 'manager_name']:
  managers[col] = managers[col].str.strip()

managers = managers.drop(columns=['key_id', 'manager_wikipedia_link'])

managers.head(3)

  manager_id family_name given_name  female country_name   manager_name
0      M-001      Acosta     Nelson       0      Uruguay  Nelson Acosta
1      M-002        Addo       Otto       0        Ghana      Otto Addo
2      M-003     Adshead       John       0      England   John Adshead

referees_cleainng

In [20]:
referees.info()
referees.isna().sum()
referees['referee_id'].duplicated().sum()
referees.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 493 entries, 0 to 492
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   key_id                  493 non-null    int64
 1   referee_id              493 non-null    str
 2   family_name             493 non-null    str
 3   given_name              493 non-null    str
 4   female                  493 non-null    int64
 5   country_name            493 non-null    str
 6   confederation_id        493 non-null    str
 7   confederation_name      493 non-null    str
 8   confederation_code      493 non-null    str
 9   referee_wikipedia_link  493 non-null    str
dtypes: int64(2), str(8)
memory usage: 38.6 KB

,key_id,referee_id,family_name,given_name,female,country_name,confederation_id,confederation_name,confederation_code,referee_wikipedia_link
0,1,R-001,Abdel-Fatah,Essam,0,Egypt,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Essam_Abd_El_Fatah
1,2,R-002,Abidoye,Bola Elizabeth,1,Nigeria,CF-2,Confederation of African Football,CAF,not available
2,3,R-003,Adair,John,0,Northern Ireland,CF-6,Union of European Football Associations,UEFA,not available

In [21]:
referees['referee_name'] = (
    referees['given_name'].fillna('')
    + ' '
    + referees['family_name'].fillna('')
).str.strip()

for col in [
    'referee_id',
    'family_name',
    'given_name',
    'country_name',
    'referee_name',
]:
  referees[col] = referees[col].str.strip()

referees = referees.drop(columns=['key_id', 'referee_wikipedia_link'])

referees.head(3)

,referee_id,family_name,given_name,female,country_name,confederation_id,confederation_name,confederation_code,referee_name
0,R-001,Abdel-Fatah,Essam,0,Egypt,CF-2,Confederation of African Football,CAF,Essam Abdel-Fatah
1,R-002,Abidoye,Bola Elizabeth,1,Nigeria,CF-2,Confederation of African Football,CAF,Bola Elizabeth Abidoye
2,R-003,Adair,John,0,Northern Ireland,CF-6,Union of European Football Associations,UEFA,John Adair

squads_cleeainng

In [22]:
squads.info()
squads.isna().sum()
squads.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 13843 entries, 0 to 13842
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           13843 non-null  int64
 1   tournament_id    13843 non-null  str
 2   tournament_name  13843 non-null  str
 3   team_id          13843 non-null  str
 4   team_name        13843 non-null  str
 5   team_code        13843 non-null  str
 6   player_id        13843 non-null  str
 7   family_name      13843 non-null  str
 8   given_name       13843 non-null  str
 9   shirt_number     13843 non-null  int64
 10  position_name    13843 non-null  str
 11  position_code    13843 non-null  str
dtypes: int64(2), str(10)
memory usage: 1.3 MB

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,player_id,family_name,given_name,shirt_number,position_name,position_code
0,1,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-69244,Bossio,Ángel,0,goal keeper,GK
1,2,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-23160,Botasso,Juan,0,goal keeper,GK
2,3,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-99230,Cherro,Roberto,0,forward,FW

In [23]:


squads = squads.drop(columns=['key_id'])

for col in squads.select_dtypes(include='object').columns:
  squads[col] = squads[col].str.strip()

squads.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\139918363.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in squads.select_dtypes(include='object').columns:

,tournament_id,tournament_name,team_id,team_name,team_code,player_id,family_name,given_name,shirt_number,position_name,position_code
0,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-69244,Bossio,Ángel,0,goal keeper,GK
1,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-23160,Botasso,Juan,0,goal keeper,GK
2,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-99230,Cherro,Roberto,0,forward,FW

teams_cleainnhg

In [24]:
teams.info()
teams.isna().sum()
teams['team_id'].duplicated().sum()
teams.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   team_id             88 non-null     str
 1   team_name           88 non-null     str
 2   team_code           88 non-null     str
 3   mens_team           88 non-null     int64
 4   womens_team         88 non-null     int64
 5   federation_name     88 non-null     str
 6   region_name         88 non-null     str
 7   confederation_id    88 non-null     str
 8   confederation_name  88 non-null     str
 9   confederation_code  88 non-null     str
dtypes: int64(2), str(8)
memory usage: 7.0 KB

,team_id,team_name,team_code,mens_team,womens_team,federation_name,region_name,confederation_id,confederation_name,confederation_code
0,T-01,Algeria,DZA,1,0,Algerian Football Federation,Africa,CF-2,Confederation of African Football,CAF
1,T-02,Angola,AGO,1,0,Angolan Football Federation,Africa,CF-2,Confederation of African Football,CAF
2,T-03,Argentina,ARG,1,1,Argentine Football Association,South America,CF-4,South American Football Confederation,CONMEBOL

In [25]:
for col in teams.select_dtypes(include='object').columns:
  teams[col] = teams[col].str.strip()

teams.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\424830942.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in teams.select_dtypes(include='object').columns:

,team_id,team_name,team_code,mens_team,womens_team,federation_name,region_name,confederation_id,confederation_name,confederation_code
0,T-01,Algeria,DZA,1,0,Algerian Football Federation,Africa,CF-2,Confederation of African Football,CAF
1,T-02,Angola,AGO,1,0,Angolan Football Federation,Africa,CF-2,Confederation of African Football,CAF
2,T-03,Argentina,ARG,1,1,Argentine Football Association,South America,CF-4,South American Football Confederation,CONMEBOL

gouls_cleainng

In [26]:
goals.info()
goals.isna().sum()
goals['goal_id'].duplicated().sum()
goals.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 3637 entries, 0 to 3636
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   key_id             3637 non-null   int64
 1   goal_id            3637 non-null   str
 2   tournament_id      3637 non-null   str
 3   tournament_name    3637 non-null   str
 4   match_id           3637 non-null   str
 5   match_name         3637 non-null   str
 6   match_date         3637 non-null   str
 7   stage_name         3637 non-null   str
 8   group_name         3637 non-null   str
 9   team_id            3637 non-null   str
 10  team_name          3637 non-null   str
 11  team_code          3637 non-null   str
 12  home_team          3637 non-null   int64
 13  away_team          3637 non-null   int64
 14  player_id          3637 non-null   str
 15  family_name        3637 non-null   str
 16  given_name         3637 non-null   str
 17  shirt_number       3637 non-null   int64
 18  player_team_id     3637 non-null   str
 19  player_team_name   3637 non-null   str
 20  player_team_code   3637 non-null   str
 21  minute_label       3637 non-null   str
 22  minute_regulation  3637 non-null   int64
 23  minute_stoppage    3637 non-null   int64
 24  match_period       3637 non-null   str
 25  own_goal           3637 non-null   int64
 26  penalty            3637 non-null   int64
dtypes: int64(8), str(19)
memory usage: 767.3 KB

,key_id,goal_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,shirt_number,player_team_id,player_team_name,player_team_code,minute_label,minute_regulation,minute_stoppage,match_period,own_goal,penalty
0,1,G-0001,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,19',19,0,first half,0,0
1,2,G-0002,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,40',40,0,first half,0,0
2,3,G-0003,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,43',43,0,first half,0,0

In [27]:
goals['match_date'] = pd.to_datetime(goals['match_date'], errors='coerce')

goals = goals.drop(columns=['key_id'])

for col in goals.select_dtypes(include='object').columns:
  goals[col] = goals[col].str.strip()

goals.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\738862639.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in goals.select_dtypes(include='object').columns:

,goal_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,shirt_number,player_team_id,player_team_name,player_team_code,minute_label,minute_regulation,minute_stoppage,match_period,own_goal,penalty
0,G-0001,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,France,...,0,T-30,France,FRA,19',19,0,first half,0,0
1,G-0002,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,France,...,0,T-30,France,FRA,40',40,0,first half,0,0
2,G-0003,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,France,...,0,T-30,France,FRA,43',43,0,first half,0,0

matches_cleainng

In [28]:
matches.info()
matches.isna().sum()
matches['match_id'].duplicated().sum()
matches.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   key_id                     1248 non-null   int64
 1   tournament_id              1248 non-null   str
 2   tournament_name            1248 non-null   str
 3   match_id                   1248 non-null   str
 4   match_name                 1248 non-null   str
 5   stage_name                 1248 non-null   str
 6   group_name                 1248 non-null   str
 7   group_stage                1248 non-null   int64
 8   knockout_stage             1248 non-null   int64
 9   replayed                   1248 non-null   int64
 10  replay                     1248 non-null   int64
 11  match_date                 1248 non-null   str
 12  match_time                 1248 non-null   str
 13  stadium_id                 1248 non-null   str
 14  stadium_name               1248 non-null   str
 15  city_name                  1248 non-null   str
 16  country_name               1248 non-null   str
 17  home_team_id               1248 non-null   str
 18  home_team_name             1248 non-null   str
 19  home_team_code             1248 non-null   str
 20  away_team_id               1248 non-null   str
 21  away_team_name             1248 non-null   str
 22  away_team_code             1248 non-null   str
 23  score                      1248 non-null   str
 24  home_team_score            1248 non-null   int64
 25  away_team_score            1248 non-null   int64
 26  home_team_score_margin     1248 non-null   int64
 27  away_team_score_margin     1248 non-null   int64
 28  extra_time                 1248 non-null   int64
 29  penalty_shootout           1248 non-null   int64
 30  score_penalties            1248 non-null   str
 31  home_team_score_penalties  1248 non-null   int64
 32  away_team_score_penalties  1248 non-null   int64
 33  result                     1248 non-null   str
 34  home_team_win              1248 non-null   int64
 35  away_team_win              1248 non-null   int64
 36  draw                       1248 non-null   int64
dtypes: int64(16), str(21)
memory usage: 360.9 KB

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [29]:
matches['match_date'] = pd.to_datetime(matches['match_date'], errors='coerce')

matches = matches.drop(columns=['key_id'])

for col in matches.select_dtypes(include='object').columns:
    matches[col] = matches[col].str.strip()

matches.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\3621448781.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in matches.select_dtypes(include='object').columns:

,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,replay,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

player_appearance cleainng

In [30]:
player_appearances.info()
player_appearances.isna().sum()
player_appearances.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 27432 entries, 0 to 27431
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           27432 non-null  int64
 1   tournament_id    27432 non-null  str
 2   tournament_name  27432 non-null  str
 3   match_id         27432 non-null  str
 4   match_name       27432 non-null  str
 5   match_date       27432 non-null  str
 6   stage_name       27432 non-null  str
 7   group_name       27432 non-null  str
 8   team_id          27432 non-null  str
 9   team_name        27432 non-null  str
 10  team_code        27432 non-null  str
 11  home_team        27432 non-null  int64
 12  away_team        27432 non-null  int64
 13  player_id        27432 non-null  str
 14  family_name      27432 non-null  str
 15  given_name       27432 non-null  str
 16  shirt_number     27432 non-null  int64
 17  position_name    27432 non-null  str
 18  position_code    27432 non-null  str
 19  starter          27432 non-null  int64
 20  substitute       27432 non-null  int64
dtypes: int64(6), str(15)
memory usage: 4.4 MB

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,home_team,away_team,player_id,family_name,given_name,shirt_number,position_name,position_code,starter,substitute
0,1,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-66980,Calderón,Ignacio,1,goal keeper,GK,1,0
1,2,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-64553,Peña,Gustavo,3,defender,DF,1,0
2,3,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-42664,Pérez,Mario,5,defender,DF,1,0

In [31]:
player_appearances['match_date'] = pd.to_datetime(player_appearances['match_date'], errors='coerce')

player_appearances = player_appearances.drop(columns=['key_id'])

for col in player_appearances.select_dtypes(include='object').columns:
    player_appearances[col] = player_appearances[col].str.strip()

player_appearances.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\640376316.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in player_appearances.select_dtypes(include='object').columns:

,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,team_code,home_team,away_team,player_id,family_name,given_name,shirt_number,position_name,position_code,starter,substitute
0,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,MEX,1,0,P-66980,Calderón,Ignacio,1,goal keeper,GK,1,0
1,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,MEX,1,0,P-64553,Peña,Gustavo,3,defender,DF,1,0
2,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,MEX,1,0,P-42664,Pérez,Mario,5,defender,DF,1,0

In [32]:
team_appearances.info()
team_appearances.isna().sum()
team_appearances.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 2496 entries, 0 to 2495
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   key_id             2496 non-null   int64
 1   tournament_id      2496 non-null   str
 2   tournament_name    2496 non-null   str
 3   match_id           2496 non-null   str
 4   match_name         2496 non-null   str
 5   stage_name         2496 non-null   str
 6   group_name         2496 non-null   str
 7   group_stage        2496 non-null   int64
 8   knockout_stage     2496 non-null   int64
 9   replayed           2496 non-null   int64
 10  replay             2496 non-null   int64
 11  match_date         2496 non-null   str
 12  match_time         2496 non-null   str
 13  stadium_id         2496 non-null   str
 14  stadium_name       2496 non-null   str
 15  city_name          2496 non-null   str
 16  country_name       2496 non-null   str
 17  team_id            2496 non-null   str
 18  team_name          2496 non-null   str
 19  team_code          2496 non-null   str
 20  opponent_id        2496 non-null   str
 21  opponent_name      2496 non-null   str
 22  opponent_code      2496 non-null   str
 23  home_team          2496 non-null   int64
 24  away_team          2496 non-null   int64
 25  goals_for          2496 non-null   int64
 26  goals_against      2496 non-null   int64
 27  goal_differential  2496 non-null   int64
 28  extra_time         2496 non-null   int64
 29  penalty_shootout   2496 non-null   int64
 30  penalties_for      2496 non-null   int64
 31  penalties_against  2496 non-null   int64
 32  result             2496 non-null   str
 33  win                2496 non-null   int64
 34  lose               2496 non-null   int64
 35  draw               2496 non-null   int64
dtypes: int64(17), str(19)
memory usage: 702.1 KB

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,goals_against,goal_differential,extra_time,penalty_shootout,penalties_for,penalties_against,result,win,lose,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,1,3,0,0,0,0,win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,4,-3,0,0,0,0,lose,0,1,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,0,3,0,0,0,0,win,1,0,0

In [33]:
team_appearances['match_date'] = pd.to_datetime(
    team_appearances['match_date'], errors='coerce'
)

team_appearances = team_appearances.drop(columns=['key_id'])

for col in team_appearances.select_dtypes(include='object').columns:
  team_appearances[col] = team_appearances[col].str.strip()

team_appearances.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\3000873317.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in team_appearances.select_dtypes(include='object').columns:

,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,replay,...,goals_against,goal_differential,extra_time,penalty_shootout,penalties_for,penalties_against,result,win,lose,draw
0,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,0,...,1,3,0,0,0,0,win,1,0,0
1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,0,...,4,-3,0,0,0,0,lose,0,1,0
2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,0,...,0,3,0,0,0,0,win,1,0,0

In [34]:
tournaments.info()
tournaments.isna().sum()
tournaments['tournament_id'].duplicated().sum()
tournaments.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tournament_id       30 non-null     str
 1   tournament_name     30 non-null     str
 2   year                30 non-null     int64
 3   start_date          30 non-null     datetime64[us]
 4   end_date            30 non-null     datetime64[us]
 5   host_country        30 non-null     str
 6   winner              30 non-null     str
 7   host_won            30 non-null     int64
 8   count_teams         30 non-null     int64
 9   group_stage         30 non-null     int64
 10  second_group_stage  30 non-null     int64
 11  final_round         30 non-null     int64
 12  round_of_16         30 non-null     int64
 13  quarter_finals      30 non-null     int64
 14  semi_finals         30 non-null     int64
 15  third_place_match   30 non-null     int64
 16  final               30 non-null     int64
dtypes: datetime64[us](2), int64(11), str(4)
memory usage: 4.1 KB

,tournament_id,tournament_name,year,start_date,end_date,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,WC-1930,1930 FIFA Men's World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,WC-1934,1934 FIFA Men's World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,WC-1938,1938 FIFA Men's World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1

In [35]:
for col in tournaments.select_dtypes(include='object').columns:
    tournaments[col] = tournaments[col].str.strip()

tournaments.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\2455444917.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in tournaments.select_dtypes(include='object').columns:

,tournament_id,tournament_name,year,start_date,end_date,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,WC-1930,1930 FIFA Men's World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,WC-1934,1934 FIFA Men's World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,WC-1938,1938 FIFA Men's World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1

In [36]:
tournament_appearances.info()
tournament_appearances.isna().sum()
tournament_appearances.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   team_name    20 non-null     str
 1   appearances  20 non-null     int64
dtypes: int64(1), str(1)
memory usage: 452.0 bytes

   team_name  appearances
0     Brazil           22
1  Argentina           18
2      Italy           18

In [37]:
tournament_appearances['team_name'] = tournament_appearances['team_name'].str.strip()
tournament_appearances.head(3)

   team_name  appearances
0     Brazil           22
1  Argentina           18
2      Italy           18

In [38]:
tournament_standings.info()
tournament_standings.isna().sum()
tournament_standings.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           120 non-null    int64
 1   tournament_id    120 non-null    str
 2   tournament_name  120 non-null    str
 3   position         120 non-null    int64
 4   team_id          120 non-null    str
 5   team_name        120 non-null    str
 6   team_code        120 non-null    str
dtypes: int64(2), str(5)
memory usage: 6.7 KB

,key_id,tournament_id,tournament_name,position,team_id,team_name,team_code
0,1,WC-1930,1930 FIFA Men's World Cup,1,T-84,Uruguay,URY
1,2,WC-1930,1930 FIFA Men's World Cup,2,T-03,Argentina,ARG
2,3,WC-1930,1930 FIFA Men's World Cup,3,T-83,United States,USA

In [39]:
tournament_standings = tournament_standings.drop(columns=['key_id'])

for col in tournament_standings.select_dtypes(include='object').columns:
    tournament_standings[col] = tournament_standings[col].str.strip()

tournament_standings.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\646928092.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in tournament_standings.select_dtypes(include='object').columns:

,tournament_id,tournament_name,position,team_id,team_name,team_code
0,WC-1930,1930 FIFA Men's World Cup,1,T-84,Uruguay,URY
1,WC-1930,1930 FIFA Men's World Cup,2,T-03,Argentina,ARG
2,WC-1930,1930 FIFA Men's World Cup,3,T-83,United States,USA

In [40]:
groups.info()
groups.isna().sum()
groups.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tournament_id    159 non-null    str
 1   tournament_name  159 non-null    str
 2   stage_number     159 non-null    int64
 3   stage_name       159 non-null    str
 4   group_name       159 non-null    str
 5   count_teams      159 non-null    int64
 6   group_id         159 non-null    str
dtypes: int64(2), str(5)
memory usage: 8.8 KB

,tournament_id,tournament_name,stage_number,stage_name,group_name,count_teams,group_id
0,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,4,WC-1930_Group 1
1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 2,3,WC-1930_Group 2
2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 3,3,WC-1930_Group 3

In [41]:
for col in groups.select_dtypes(include='object').columns:
    groups[col] = groups[col].str.strip()

groups.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\1715118199.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in groups.select_dtypes(include='object').columns:

,tournament_id,tournament_name,stage_number,stage_name,group_name,count_teams,group_id
0,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,4,WC-1930_Group 1
1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 2,3,WC-1930_Group 2
2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 3,3,WC-1930_Group 3

In [42]:
group_standings.info()
group_standings.isna().sum()
group_standings.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           626 non-null    int64
 1   tournament_id    626 non-null    str
 2   tournament_name  626 non-null    str
 3   stage_number     626 non-null    int64
 4   stage_name       626 non-null    str
 5   group_name       626 non-null    str
 6   position         626 non-null    int64
 7   team_id          626 non-null    str
 8   team_name        626 non-null    str
 9   team_code        626 non-null    str
 10  played           626 non-null    int64
 11  wins             626 non-null    int64
 12  draws            626 non-null    int64
 13  losses           626 non-null    int64
 14  goals_for        626 non-null    int64
 15  goals_against    626 non-null    int64
 16  goal_difference  626 non-null    int64
 17  points           626 non-null    int64
 18  advanced         626 non-null    int64
dtypes: int64(12), str(7)
memory usage: 93.1 KB

,key_id,tournament_id,tournament_name,stage_number,stage_name,group_name,position,team_id,team_name,team_code,played,wins,draws,losses,goals_for,goals_against,goal_difference,points,advanced
0,1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,1,T-03,Argentina,ARG,3,3,0,0,10,4,6,6,1
1,2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,2,T-13,Chile,CHL,3,2,0,1,5,3,2,4,0
2,3,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,3,T-30,France,FRA,3,1,0,2,4,3,1,2,0

In [43]:
group_standings = group_standings.drop(columns=['key_id'])

for col in group_standings.select_dtypes(include='object').columns:
    group_standings[col] = group_standings[col].str.strip()

group_standings.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\3780639177.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in group_standings.select_dtypes(include='object').columns:

,tournament_id,tournament_name,stage_number,stage_name,group_name,position,team_id,team_name,team_code,played,wins,draws,losses,goals_for,goals_against,goal_difference,points,advanced
0,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,1,T-03,Argentina,ARG,3,3,0,0,10,4,6,6,1
1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,2,T-13,Chile,CHL,3,2,0,1,5,3,2,4,0
2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,3,T-30,France,FRA,3,1,0,2,4,3,1,2,0

In [44]:
qualified_teams.info()
qualified_teams.isna().sum()
qualified_teams.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           625 non-null    int64
 1   tournament_id    625 non-null    str
 2   tournament_name  625 non-null    str
 3   team_id          625 non-null    str
 4   team_name        625 non-null    str
 5   team_code        625 non-null    str
 6   count_matches    625 non-null    int64
 7   performance      625 non-null    str
dtypes: int64(2), str(6)
memory usage: 39.2 KB

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,count_matches,performance
0,1,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,5,final
1,2,WC-1930,1930 FIFA Men's World Cup,T-06,Belgium,BEL,2,group stage
2,3,WC-1930,1930 FIFA Men's World Cup,T-07,Bolivia,BOL,2,group stage

In [45]:
qualified_teams = qualified_teams.drop(columns=['key_id'])

for col in qualified_teams.select_dtypes(include='object').columns:
    qualified_teams[col] = qualified_teams[col].str.strip()

qualified_teams.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\609951372.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in qualified_teams.select_dtypes(include='object').columns:

,tournament_id,tournament_name,team_id,team_name,team_code,count_matches,performance
0,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,5,final
1,WC-1930,1930 FIFA Men's World Cup,T-06,Belgium,BEL,2,group stage
2,WC-1930,1930 FIFA Men's World Cup,T-07,Bolivia,BOL,2,group stage

In [46]:
attendance.info()
attendance.isna().sum()
attendance.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        964 non-null    int64
 1   stage       964 non-null    str
 2   phase       964 non-null    str
 3   date        964 non-null    str
 4   team1       964 non-null    str
 5   team2       964 non-null    str
 6   score       964 non-null    str
 7   attendance  964 non-null    int64
 8   stadium     964 non-null    str
 9   city        964 non-null    str
 10  source      964 non-null    str
dtypes: int64(2), str(9)
memory usage: 83.0 KB

,year,stage,phase,date,team1,team2,score,attendance,stadium,city,source
0,1930,Group 1,Group,1930-07-13,France,Mexico,4-1,4444,Pocitos,Montevideo,"Kaggle/FIFA WorldCupMatches (1930–2010), cross..."
1,1930,Group 4,Group,1930-07-13,USA,Belgium,3-0,18346,Parque Central,Montevideo,"Kaggle/FIFA WorldCupMatches (1930–2010), cross..."
2,1930,Group 2,Group,1930-07-14,Yugoslavia,Brazil,2-1,24059,Parque Central,Montevideo,"Kaggle/FIFA WorldCupMatches (1930–2010), cross..."

In [47]:
attendance['date'] = pd.to_datetime(attendance['date'], errors='coerce')

for col in attendance.select_dtypes(include='object').columns:
    attendance[col] = attendance[col].str.strip()

attendance.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\2227871874.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in attendance.select_dtypes(include='object').columns:

,year,stage,phase,date,team1,team2,score,attendance,stadium,city,source
0,1930,Group 1,Group,1930-07-13,France,Mexico,4-1,4444,Pocitos,Montevideo,"Kaggle/FIFA WorldCupMatches (1930–2010), cross..."
1,1930,Group 4,Group,1930-07-13,USA,Belgium,3-0,18346,Parque Central,Montevideo,"Kaggle/FIFA WorldCupMatches (1930–2010), cross..."
2,1930,Group 2,Group,1930-07-14,Yugoslavia,Brazil,2-1,24059,Parque Central,Montevideo,"Kaggle/FIFA WorldCupMatches (1930–2010), cross..."

In [48]:
attendance_by_edition = pd.read_csv('attendance-by-edition.csv')  # أو بالاسم الذي عرفته به
attendance_by_edition.info()
attendance_by_edition.isna().sum()
attendance_by_edition.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              22 non-null     int64
 1   tournament_name   22 non-null     str
 2   matches           22 non-null     int64
 3   total_attendance  22 non-null     int64
 4   avg_attendance    22 non-null     int64
dtypes: int64(4), str(1)
memory usage: 1012.0 bytes

   year            tournament_name  matches  total_attendance  avg_attendance
0  1930  1930 FIFA Men's World Cup       18            590549           32808
1  1934  1934 FIFA Men's World Cup       17            363000           21353
2  1938  1938 FIFA Men's World Cup       18            375700           20872

In [49]:
for col in attendance_by_edition.select_dtypes(include='object').columns:
    attendance_by_edition[col] = attendance_by_edition[col].str.strip()

attendance_by_edition.head(3)

C:\Users\mohamed\AppData\Local\Temp\ipykernel_20116\2851625000.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in attendance_by_edition.select_dtypes(include='object').columns:

   year            tournament_name  matches  total_attendance  avg_attendance
0  1930  1930 FIFA Men's World Cup       18            590549           32808
1  1934  1934 FIFA Men's World Cup       17            363000           21353
2  1938  1938 FIFA Men's World Cup       18            375700           20872

In [ ]:
import os

# إنشاء مجلد للبيانات المنظفة
os.makedirs('cleaned_fifa_data', exist_ok=True)

# قائمة بكل الـ DataFrames بعد التنظيف
dfs = {
    'stadiums': stadiums,
    'players': players,
    'managers': managers,
    'referees': referees,
    'squads': squads,
    'teams': teams,
    'goals': goals,
    'matches': matches,
    'player_appearances': player_appearances,
    'team_appearances': team_appearances,
    'tournaments': tournaments,
    'tournament_appearances': tournament_appearances,
    'tournament_standings': tournament_standings,
    'groups': groups,
    'group_standings': group_standings,
    'qualified_teams': qualified_teams,
    'attendance': attendance,
    'attendance_by_edition': attendance_by_edition,
}


for name, df in dfs.items():
  df.to_csv(f'cleaned_fifa_data/{name}.csv', index=False)

تم تصدير جميع الجداول بنجاح!

In [52]:
 
print("أعمدة goals:", goals.columns.tolist())
print("أعمدة players:", players.columns.tolist())

أعمدة goals: ['goal_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'player_team_id', 'player_team_name', 'player_team_code', 'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'own_goal', 'penalty']
أعمدة players: ['player_id', 'family_name', 'given_name', 'birth_date', 'female', 'goal_keeper', 'defender', 'midfielder', 'forward', 'count_tournaments', 'list_tournaments', 'player_name']

In [58]:
clean_given = goals['given_name'].replace('not applicable', '').fillna('').str.strip()
clean_family = goals['family_name'].replace('not applicable', '').fillna('').str.strip()

goals['clean_name'] = (clean_given + ' ' + clean_family).str.strip()


top_men = goals[(goals['own_goal'] == 0) & (goals['tournament_name'].str.contains("Men's", case=False, na=False))]['clean_name'].value_counts().head(10)

 

print("--- Top 10 men---")
print(top_men)

--- Top 10 men---
clean_name
Marta             17
Miroslav Klose    16
Ronaldo           15
Gerd Müller       14
Birgit Prinz      14
Abby Wambach      14
Just Fontaine     13
Lionel Messi      13
Pelé              12
Michelle Akers    12
Name: count, dtype: int64